name: ask-me-anything

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${AMA_DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${AMA_DATABASE_USER}
      POSTGRES_PASSWORD: ${AMA_DATABASE_PASSWORD}
      POSTGRES_DB: ${AMA_DATABASE_NAME}
    volumes:
      - ama-db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - ${AMA_PGADMIN_PORT:-5050}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${AMA_PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${AMA_PGADMIN_PASSWORD}
    volumes:
      - ama-pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  ama-db-data:
    driver: local
  ama-pgadmin-data:
    driver: local
