version: "2"
sql:
  - engine: "postgresql"
    queries: "../internal/database/pgdb/queries"
    schema: "../internal/database/pgdb/migrations"
    gen:
      go:
        package: "pgdb"
        out: "../internal/database/pgdb"
        sql_package: "pgx/v5"
        overrides:
          - db_type: "uuid"
            go_type:
              import: "github.com/google/uuid"
              type: "UUID"
